### ISSUE TITLE
Project is not working with API > 2.9

### ISSUE THREAD

**Issue by ppodgorsek** [ppodgorsek/spring-social-facebook#1]
The following exception is thrown with later API calls:

>	org.springframework.social.UncategorizedApiException: (#100) Tried accessing nonexisting field (context) on node type (User)
>	at org.springframework.social.facebook.api.impl.FacebookErrorHandler.handleFacebookError(FacebookErrorHandler.java:91) ~[spring-social-facebook-3.0.0.M3.jar:3.0.0.M3]
>	at org.springframework.social.facebook.api.impl.FacebookErrorHandler.handleError(FacebookErrorHandler.java:59) ~[spring-social-facebook-3.0.0.M3.jar:3.0.0.M3]
>	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
>	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:778) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
>	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:736) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
>	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:710) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
>	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:329) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
>	at org.springframework.social.facebook.api.impl.FacebookTemplate.fetchObject(FacebookTemplate.java:220) ~[spring-social-facebook-3.0.0.M3.jar:3.0.0.M3]
>	at org.springframework.social.facebook.api.impl.FacebookTemplate.fetchObject(FacebookTemplate.java:215) ~[spring-social-facebook-3.0.0.M3.jar:3.0.0.M3]
>	at org.springframework.social.facebook.api.impl.UserTemplate.getUserProfile(UserTemplate.java:53) ~[spring-social-facebook-3.0.0.M3.jar:3.0.0.M3]
>	at org.springframework.social.facebook.api.impl.UserTemplate.getUserProfile(UserTemplate.java:49) ~[spring-social-facebook-3.0.0.M3.jar:3.0.0.M3]
>	at org.springframework.social.facebook.connect.FacebookAdapter.fetchUserProfile(FacebookAdapter.java:50) ~[spring-social-facebook-3.0.0.M3.jar:3.0.0.M3]
>	at org.springframework.social.facebook.connect.FacebookAdapter.fetchUserProfile(FacebookAdapter.java:30) ~[spring-social-facebook-3.0.0.M3.jar:3.0.0.M3]
>	at org.springframework.social.connect.support.AbstractConnection.fetchUserProfile(AbstractConnection.java:111) ~[spring-social-core-2.0.0.M4.jar:2.0.0.M4]

**Comment by ppodgorsek** [comment]
Relates to:
* https://github.com/spring-projects/spring-social-facebook/issues/277
* https://github.com/spring-projects/spring-social-facebook/issues/278
* https://github.com/spring-projects/spring-social-facebook/pull/279

**Comment by ppodgorsek** [comment]
Fixed
